name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '22.3.0'

    - name: Check for composer.json
      run: |
        if [ ! -f composer.json ]; then
          echo "composer.json not found!"
          exit 1
        fi
  
    - name: Install PHP dependencies
      run: composer install

    - name: Install Node.js dependencies
      run: npm install
        
    - name: Build CSS with Tailwind
      run: npm run watch:css

    - name: Run tests
      run: composer test

    - name: Deploy to Vercel
      env:
        VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        # VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      run: |
        npm install -g vercel
        vercel --token $VERCEL_TOKEN --prod --confirm
